#pragma once

#define DRAG_FLOAT_UNIT 0.01f

#define IMPACT_SPEED_MIN 0.0f
#define IMPACT_SPEED_MAX 10.0f

#define IMPACT_SIZE_MIN 0.0f
#define IMPACT_SIZE_MAX 10.0f

#define IMPACT_ALPHA_MIN 0.0f
#define IMPACT_ALPHA_MAX 10.0f

#define PARTICLE_SIZE_MIN 0.0f
#define PARTICLE_SIZE_MAX 10.0f

#define PARTICLE_ALPHA_MIN 0.0f
#define PARTICLE_ALPHA_MAX 10.0f

#define PARTICLE_LIFETIME_MIN 0.0f
#define PARTICLE_LIFETIME_MAX 10.0f

#define PARTICLE_COUNT_MIN 0
#define PARTICLE_COUNT_MAX 500

#define PARTICLE_SPEED_MIN 0.0f
#define PARTICLE_SPEED_MAX 200.0f

#define DAMAGE_ANIMATION_DISTANCE_MIN 0.0f
#define DAMAGE_ANIMATION_DISTANCE_MAX 10.0f

#define DAMAGE_ANIMATION_SPEED_MIN 0.0f
#define DAMAGE_ANIMATION_SPEED_MAX 200.0f

#define SHAKE_ANIMATION_DURATION_MIN 0.0f
#define SHAKE_ANIMATION_DURATION_MAX 10.0f

#define SHAKE_ANIMATION_DISTANCE_MIN 0.0f
#define SHAKE_ANIMATION_DISTANCE_MAX 10.0f

#define SHAKE_ANIMATION_FREQUENCY_MIN 0.0f
#define SHAKE_ANIMATION_FREQUENCY_MAX 1.0f

#define STUN_ANIMATION_STUNTIME_MIN 0.0f
#define STUN_ANIMATION_STUNTIME_MAX 0.0f

#define HIT_LAG_MAXTIME_MIN 0.0f
#define HIT_LAG_MAXTIME_MAX 1.0f

#define HIT_LAG_SCALEWEIGHT_MIN 0.1f
#define HIT_LAG_SCALEWEIGHT_MAX 1.0f

#define CAMERA_MOVE_DISTANCE_MIN 0.0f
#define CAMERA_MOVE_DISTANCE_MAX 10.0f

#define CAMERA_MOVE_TIME_MIN 0.0f
#define CAMERA_MOVE_TIME_MAX 10.0f

#define CAMERA_MOVE_ROLLBACKTIME_MIN 0.0f
#define CAMERA_MOVE_ROLLBACKTIME_MAX 10.0f

#define CAMERA_SHAKE_MAGNITUDE_MIN 0.0f
#define CAMERA_SHAKE_MAGNITUDE_MAX 10.0f

#define CAMERA_SHAKE_DURATION_MIN 0.0f
#define CAMERA_SHAKE_DURATION_MAX 10.0f

#define CAMERA_SHAKE_FREQUENCY_MIN 0.0f
#define CAMERA_SHAKE_FREQUENCY_MAX 10.0f

#define CAMERA_ZOOMINOUT_DISTANCE_MIN 0.0f
#define CAMERA_ZOOMINOUT_DISTANCE_MAX 10.0f

#define CAMERA_ZOOMINOUT_TIME_MIN 0.0f
#define CAMERA_ZOOMINOUT_TIME_MAX 10.0f

#define CAMERA_ZOOMINOUT_ROLLBACKTIME_MIN 0.0f
#define CAMERA_ZOOMINOUT_ROLLBACKTIME_MAX 10.0f

#define SHOCK_SOUND_DELAY_MIN 0.0f
#define SHOCK_SOUND_DELAY_MAX 10.0f

#define SHOCK_SOUND_VOLUME_MIN 0.0f
#define SHOCK_SOUND_VOLUME_MAX 10.0f

#define SHOOTING_SOUND_DELAY_MIN 0.0f
#define SHOOTING_SOUND_DELAY_MAX 10.0f

#define SHOOTING_SOUND_VOLUME_MIN 0.0f
#define SHOOTING_SOUND_VOLUME_MAX 10.0f

#define MOAN_SOUND_DELAY_MIN 0.0f
#define MOAN_SOUND_DELAY_MAX 10.0f

#define MOAN_SOUND_VOLUME_MIN 0.0f
#define MOAN_SOUND_VOLUME_MAX 10.0f








