#pragma once
#pragma once

#define IMPACT_TEXTURE_INDEX_DEFAULT 7
#define IMPACT_LIFETIME_DEFAULT 0.5f
#define IMPACT_ALPHA_DEFAULT 1.0f
#define IMPACT_SIZEX_DEFAULT 5.0f
#define IMPACT_SIZEY_DEFAULT 5.0f
#define IMPACT_COLOR_R_DEFAULT 0.9882352941176471f
#define IMPACT_COLOR_G_DEFAULT 0.4784313725490196f
#define IMPACT_COLOR_B_DEFAULT 0.0784313725490196f
#define IMPACT_EMISSIVE_DEFAULT 4.0f

#define PARTICLE_TEXTURE_INDEX_DEFAULT 7
#define PARTICLE_SIZEX_DEFAULT 5.f
#define PARTICLE_SIZEY_DEFAULT 5.0f
#define PARTICLE_ALPHA_DEFAULT 1.f
#define PARTICLE_LIFETIME_DEFAULT 1.0f
#define PARTICLE_COUNT_DEFAULT 30
#define PARTICLE_SPEED_DEFAULT 40
#define PARTICLE_COLOR_R_DEFAULT 0.8745098039215686f
#define PARTICLE_COLOR_G_DEFAULT 0.6980392156862745f
#define PARTICLE_COLOR_B_DEFAULT 0.1215686274509804f
#define PARTICLE_EMISSIVE_DEFAULT 15.f
#define PARTICLE_SIMULATEROTATE_DEFAULT true
#define PARTICLE_NOISESTRENGTH_DEFAULT 1.0f;

#define SLASH_TEXTURE_INDEX_DEFAULT 0
#define SLASH_SIZEX_DEFAULT 0.7f
#define SLASH_SIZEY_DEFAULT 15.f
#define SLASH_ALPHA_DEFAULT 1.f
#define SLASH_LIFETIME_DEFAULT 0.5f
#define SLASH_COLOR_R_DEFAULT 1.0f
#define SLASH_COLOR_G_DEFAULT 0.4627450980392157f
#define SLASH_COLOR_B_DEFAULT 0.f
#define SLASH_EMISSIVE_DEFAULT 10.f

#define TRAIL_TEXTURE_INDEX_DEFAULT 0
#define TRAIL_EMISSIVE_DEFAULT 20.f
#define TRAIL_CURVES_DEFAULT 4
#define TRAIL_NOISETEXTURE_INDEX_DEFAULT 0

#define DAMAGE_ANIMATION_DISTANCE_DEFAULT 1.0f
#define DAMAGE_ANIMATION_SPEED_DEFAULT 25.0f

#define SHAKE_ANIMATION_DURATION_DEFAULT 0.8f
#define SHAKE_ANIMATION_DISTANCE_DEFAULT 0.1f
#define SHAKE_ANIMATION_FREQUENCY_DEFAULT 0.01f

#define STUN_ANIMATION_STUNTIME_DEFAULT 0.4f

#define HIT_LAG_MAXTIME_DEFAULT 0.5f
#define HIT_LAG_DURATION_DEFAULT 0.5f
#define HIT_LAG_SCALEWEIGHT_DEFAULT 0.5f

#define CAMERA_MOVE_DISTANCE_DEFAULT 0.6f
#define CAMERA_MOVE_TIME_DEFAULT 0.1f
#define CAMERA_MOVE_ROLLBACKTIME_DEFAULT 0.05f

#define CAMERA_SHAKE_MAGNITUDE_DEFAULT 0.5f
#define CAMERA_SHAKE_DURATION_DEFAULT 0.5f
#define CAMERA_SHAKE_FREQUENCY_DEFAULT 0.015f

#define CAMERA_ZOOMOUT_DISTANCE_DEFAULT 1.0f
#define CAMERA_ZOOMOUT_TIME_DEFAULT 0.08f
#define CAMERA_ZOOMOUT_ROLLBACKTIME_DEFAULT 0.02f
#define CAMERA_ZOOMOUT_ISIN_DEFAULT false

#define SHOCK_SOUND_SOUNDNUMBER_DEFAULT 8
#define SHOCK_SOUND_DELAY_DEFAULT 0.0f
#define SHOCK_SOUND_VOLUME_DEFAULT 0.4f

#define SHOOTING_SOUND_SOUNDNUMBER_DEFAULT 2
#define SHOOTING_SOUND_DELAY_DEFAULT 0.2f
#define SHOOTING_SOUND_VOLUME_DEFAULT  1.1f

#define GOBLIN_MOAN_SOUND_SOUNDNUMBER_DEFAULT 0
#define GOBLIN_MOAN_SOUND_DELAY_DEFAULT 0.f
#define GOBLIN_MOAN_SOUND_VOLUME_DEFAULT 0.75f

#define ORC_MOAN_SOUND_SOUNDNUMBER_DEFAULT 3
#define ORC_MOAN_SOUND_DELAY_DEFAULT 0.f
#define ORC_MOAN_SOUND_VOLUME_DEFAULT 0.75f

#define SKELETON_MOAN_SOUND_SOUNDNUMBER_DEFAULT 0
#define SKELETON_MOAN_SOUND_DELAY_DEFAULT 0.f
#define SKELETON_MOAN_SOUND_VOLUME_DEFAULT 0.75f