#pragma once
#pragma once

#define IMPACT_TEXTURE_INDEX_DEFAULT 3
#define IMPACT_LIFETIME_DEFAULT 0.7f
#define IMPACT_ALPHA_DEFAULT 1.0f
#define IMPACT_SIZEX_DEFAULT 8.0f
#define IMPACT_SIZEY_DEFAULT 8.0f
#define IMPACT_COLOR_R_DEFAULT 0.3333333333333333f
#define IMPACT_COLOR_G_DEFAULT 0.4392156862745098f
#define IMPACT_COLOR_B_DEFAULT 0.5137254901960784f
#define IMPACT_EMISSIVE_DEFAULT 7.0f

#define PARTICLE_TEXTURE_INDEX_DEFAULT 6
#define PARTICLE_SIZEX_DEFAULT 0.3f
#define PARTICLE_SIZEY_DEFAULT 0.6f
#define PARTICLE_ALPHA_DEFAULT 1.f
#define PARTICLE_LIFETIME_DEFAULT 1.f
#define PARTICLE_COUNT_DEFAULT 25
#define PARTICLE_SPEED_DEFAULT 30
#define PARTICLE_COLOR_R_DEFAULT 0.9215686274509804f
#define PARTICLE_COLOR_G_DEFAULT 0.6431372549019608f
#define PARTICLE_COLOR_B_DEFAULT 0.3529411764705882f
#define PARTICLE_EMISSIVE_DEFAULT 5.f
#define PARTICLE_SIMULATEROTATE_DEFAULT true
#define PARTICLE_NOISESTRENGTH_DEFAULT 0.05f;

#define SLASH_TEXTURE_INDEX_DEFAULT 8
#define SLASH_SIZEX_DEFAULT 1.f
#define SLASH_SIZEY_DEFAULT 20.f
#define SLASH_ALPHA_DEFAULT 1.f
#define SLASH_LIFETIME_DEFAULT 0.5f
#define SLASH_COLOR_R_DEFAULT 0.9411764705882353f
#define SLASH_COLOR_G_DEFAULT 0.5686274509803922f
#define SLASH_COLOR_B_DEFAULT 0.1450980392156863f
#define SLASH_EMISSIVE_DEFAULT 20.f

#define TRAIL_TEXTURE_INDEX_DEFAULT 2
#define TRAIL_EMISSIVE_DEFAULT 15.f
#define TRAIL_CURVES_DEFAULT 4
#define TRAIL_NOISETEXTURE_INDEX_DEFAULT 2

#define DAMAGE_ANIMATION_DISTANCE_DEFAULT 0.65f
#define DAMAGE_ANIMATION_SPEED_DEFAULT 3.8f

#define SHAKE_ANIMATION_DURATION_DEFAULT 0.3f
#define SHAKE_ANIMATION_DISTANCE_DEFAULT 0.15f
#define SHAKE_ANIMATION_FREQUENCY_DEFAULT 0.025f

#define STUN_ANIMATION_STUNTIME_DEFAULT 0.1f

#define HIT_LAG_MAXTIME_DEFAULT 0.25f
#define HIT_LAG_DURATION_DEFAULT 0.5f
#define HIT_LAG_SCALEWEIGHT_DEFAULT 0.8f

#define CAMERA_MOVE_DISTANCE_DEFAULT 0.6f
#define CAMERA_MOVE_TIME_DEFAULT 0.1f
#define CAMERA_MOVE_ROLLBACKTIME_DEFAULT 0.05f

#define CAMERA_SHAKE_MAGNITUDE_DEFAULT 0.1f
#define CAMERA_SHAKE_DURATION_DEFAULT 0.27f
#define CAMERA_SHAKE_FREQUENCY_DEFAULT 0.045f

#define CAMERA_ZOOMOUT_DISTANCE_DEFAULT 1.0f
#define CAMERA_ZOOMOUT_TIME_DEFAULT 0.08f
#define CAMERA_ZOOMOUT_ROLLBACKTIME_DEFAULT 0.02f
#define CAMERA_ZOOMOUT_ISIN_DEFAULT false

#define SHOCK_SOUND_SOUNDNUMBER_DEFAULT 1
#define SHOCK_SOUND_DELAY_DEFAULT 0.0f
#define SHOCK_SOUND_VOLUME_DEFAULT 0.45f

#define SHOOTING_SOUND_SOUNDNUMBER_DEFAULT 1
#define SHOOTING_SOUND_DELAY_DEFAULT 0.43f
#define SHOOTING_SOUND_VOLUME_DEFAULT  1.25f

#define GOBLIN_MOAN_SOUND_SOUNDNUMBER_DEFAULT 3
#define GOBLIN_MOAN_SOUND_DELAY_DEFAULT 0.f
#define GOBLIN_MOAN_SOUND_VOLUME_DEFAULT 0.45f

#define ORC_MOAN_SOUND_SOUNDNUMBER_DEFAULT 3
#define ORC_MOAN_SOUND_DELAY_DEFAULT 0.f
#define ORC_MOAN_SOUND_VOLUME_DEFAULT 0.55f

#define SKELETON_MOAN_SOUND_SOUNDNUMBER_DEFAULT 8
#define SKELETON_MOAN_SOUND_DELAY_DEFAULT 0.f
#define SKELETON_MOAN_SOUND_VOLUME_DEFAULT 0.3f