#pragma once
#pragma once

#define IMPACT_TEXTURE_INDEX_DEFAULT 0
#define IMPACT_LIFETIME_DEFAULT 0.0f
#define IMPACT_ALPHA_DEFAULT 0.0f
#define IMPACT_SIZEX_DEFAULT 0.0f
#define IMPACT_SIZEY_DEFAULT 0.0f
#define IMPACT_COLOR_R_DEFAULT 0.0f
#define IMPACT_COLOR_G_DEFAULT 0.0f
#define IMPACT_COLOR_B_DEFAULT 0.0f
#define IMPACT_EMISSIVE_DEFAULT 0.0f

#define PARTICLE_SIZE_DEFAULT 0.0f
#define PARTICLE_ALPHA_DEFAULT 0.0f
#define PARTICLE_LIFETIME_DEFAULT 0.0f
#define PARTICLE_SPEED_DEFAULT 0.0f
#define PARTICLE_COUNT_DEFAULT 0

#define SLASH_SIZE_DEFAULT 0.0f

#define DAMAGE_ANIMATION_DISTANCE_DEFAULT 0.0f
#define DAMAGE_ANIMATION_SPEED_DEFAULT 0.0f

#define SHAKE_ANIMATION_DURATION_DEFAULT 0.0f
#define SHAKE_ANIMATION_DISTANCE_DEFAULT 0.0f
#define SHAKE_ANIMATION_FREQUENCY_DEFAULT 0.0f

#define STUN_ANIMATION_STUNTIME_DEFAULT 0.0f

#define HIT_LAG_MAXTIME_DEFAULT 0.0f
#define HIT_LAG_DURATION_DEFAULT 0.0f
#define HIT_LAG_SCALEWEIGHT_DEFAULT 0.1f

#define CAMERA_MOVE_DISTANCE_DEFAULT 0.0f
#define CAMERA_MOVE_TIME_DEFAULT 0.0f
#define CAMERA_MOVE_ROLLBACKTIME_DEFAULT 0.0f

#define CAMERA_SHAKE_MAGNITUDE_DEFAULT 0.0f
#define CAMERA_SHAKE_DURATION_DEFAULT 0.0f
#define CAMERA_SHAKE_FREQUENCY_DEFAULT 0.0f

#define CAMERA_ZOODEFAULTOUT_DISTANCE_DEFAULT 0.0f
#define CAMERA_ZOODEFAULTOUT_TIME_DEFAULT 0.0f
#define CAMERA_ZOODEFAULTOUT_ROLLBACKTIME_DEFAULT 0.0f

#define SHOCK_SOUND_DELAY_DEFAULT 0.0f
#define SHOCK_SOUND_VOLUME_DEFAULT 0.0f

#define SHOOTING_SOUND_DELAY_DEFAULT 0.0f
#define SHOOTING_SOUND_VOLUME_DEFAULT 0.0f

#define MOAN_SOUND_DELAY_DEFAULT 0.0f
#define MOAN_SOUND_VOLUME_DEFAULT 0.0f